all: pascal_triangle pascal_matrix

pascal_triangle:
	gcc -Wall -Wextra -Werror -std=c11 -o ../bin/pascal_triangle pascal_triangle.c
pascal_matrix:
	gcc -Wall -Wextra -Werror -std=c11 -o ../bin/pascal_matrix pascal_matrix.c

